name: $(Build.SourceBranchName).$(date:yyyyMMdd)$(rev:.r)

variables:
  project.name: "Continuos_resilience _chaos_enginnering"
  project.application-code: "OPS0112001"
  sonar.project: $(project.name)_$(project.application-code)

trigger:
  branches:
    include:
      - main

pool:
  name: Azure Pipelines
  demands: java

steps:
- script: echo Hello, world!
  displayName: 'Hello world'

- task: JavaToolInstaller@1
  displayName: 'Use Java 17'
  inputs:
    versionSpec: 17
    jdkArchitectureOption: x64
    jdkSourceOption: PreInstalled

- task: SonarQubePrepare@6
  displayName: "Prepare analysis on SonarQube"
  inputs:
    SonarQube: SonarQube
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: $(sonar.project)
    cliProjectName: $(sonar.project)
    cliProjectVersion: "$(Build.BuildNumber)"
    extraProperties: |
      sonar.java.binaries=$(spring-root-path)/chaos-monkey-spring-boot/target/classes/de/codecentric/spring/boot/chaos/monkey
      sonar.coverage.jacoco.xmlReportPaths=$(spring-root-path)/chaos-monkey-spring-boot/target/site/jacoco/jacoco.xml
      sonar.junit.reportsPaths=$(spring-root-path)/chaos-monkey-spring-boot/target\surefire-reports

      sonar.sourceEncoding=UTF-8
      sonar.coverage.exclusions=**/*.js, **/*.html, **/*.xml, **/*.adoc, **/*.png ,**/*.json, **/*.properties, **/*.yaml, **/*.yml, **/*.txt, **/*.css, **/*.scss, **/*.md, **/*.gitignore, **/*.dockerignore, **/*.sh, **/*.log, **/applications/**/*, **/config/**/*, **/exception/**/*, **/acceptance-test/**/*, **/r2dbc/**/*, **/metrics/**,

- task: SonarQubeAnalyze@7
  displayName: "Run Code Analysis"

- task: sonar-buildbreaker@8
  displayName: "Break build on quality gate failure"
  inputs:
    SonarQube: SonarQube

- task: CopyFiles@2
  displayName: 'Copy Jar'
  inputs:
    SourceFolder: '$(spring-root-path)/chaos-monkey-spring-boot/target'
    Contents: 'chaos-monkey-spring-boot-3.1.1-SNAPSHOT-jar-with-dependencies.jar'
    TargetFolder: '$(spring-root-path)/docker'
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/trunk'), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/tdev')))

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Artifact'
  inputs:
    PathtoPublish: '$(spring-root-path)/docker'
    ArtifactName: Artifact
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/trunk'), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/tdev')))
